### PR TITLE
add !important option

### PR DESCRIPTION
**Pull request by krispy1298**

### CODE REVIEW

**Comment by alexsomeoddpilot** [comment]
Can you write a test for this?

* https://github.com/alexsomeoddpilot/sop-styl/blob/master/test/cases/font.styl

**Comment by krispy1298** [comment]
how do i test this?

On Tue, Mar 31, 2015 at 12:25 PM, Alex Robertson <notifications@github.com>
wrote:

> Can you write a test for this?
>
>    -
>    https://github.com/alexsomeoddpilot/sop-styl/blob/master/test/cases/font.styl
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexsomeoddpilot/sop-styl/pull/2#issuecomment-88178073>
> .
>



-- 

Kamil Kecki // Designer
kamilkecki.com
hello@kamilkecki.com

**Comment by alexsomeoddpilot** [comment]
`npm test` or `mocha`

On Tue, Mar 31, 2015 at 1:10 PM, Kamil Kecki <notifications@github.com>
wrote:

> how do i test this?
>
> On Tue, Mar 31, 2015 at 12:25 PM, Alex Robertson <notifications@github.com
> >
> wrote:
>
> > Can you write a test for this?
> >
> > -
> >
> https://github.com/alexsomeoddpilot/sop-styl/blob/master/test/cases/font.styl
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/alexsomeoddpilot/sop-styl/pull/2#issuecomment-88178073>
> > .
> >
>
>
>
> --
>
> Kamil Kecki // Designer
> kamilkecki.com
> hello@kamilkecki.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexsomeoddpilot/sop-styl/pull/2#issuecomment-88193265>
> .
>



-- 

*Alex Robertson*
alex@someoddpilot.com

*Someoddpilot*
1539 N. Damen Ave. 2nd Floor
Chicago, IL 60622
Ph. (773) 529-7128
Fx. (877) 350-3750
http://www.someoddpilot.com
http://www.thispublicworks.com

**Comment by alexsomeoddpilot** [comment]
I'm not sure if there's a better way to accomplish this. `!important` is generally avoided, so I don’t think Stylus gives us easy tools to add it to every property in a block.

**Pull request merged**
